- hosts: all
  user: test
  become: true
  become_method: sudo
  become_user: root
  vars:
    - packages:
         - mc

  tasks:
    - name: Uninstall Packages Centos
      yum:
         name: "{{ packages }}"
         state: absent
      when: ansible_distribution == "CentOS"
    - name: Uninstall Packages Ubuntu
      apt:
        name: "{{ packages }}"
        state: absent
      when: ansible_distribution == "Ubuntu"
